# Generated by Django 3.0.2 on 2020-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_cardetail_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='location',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
